# permissions for end users to edit redissentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redissentinel-editor-role
rules:
- apiGroups:
  - redis.kdcloud.io
  resources:
  - redissentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.kdcloud.io
  resources:
  - redissentinels/status
  verbs:
  - get
