# permissions for end users to view redissentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redissentinel-viewer-role
rules:
- apiGroups:
  - redis.kdcloud.io
  resources:
  - redissentinels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.kdcloud.io
  resources:
  - redissentinels/status
  verbs:
  - get
